import { FarmerRecord, DPCLocationCenter, ProcurementAppointment, TalukOverflowMetric, SMSLog } from '@/types';

export const INITIAL_FARMER_RECORDS: FarmerRecord[] = [
  {
    id: "FARMER-101",
    registrationNumber: "TN-REG-2026-4821",
    aadhaarNumber: "8810 2948 1920",
    pmKisanId: "PMK-TN-981240",
    uzhavanId: "UZH-TNJ-2026-9014",
    name: "Murugan Swaminathan",
    nameTa: "முருகன் சுவாமிநாதன்",
    phone: "+91 94431 82910",
    registrationOffice: "PACCS Thiruvaiyaru Cooperative Bank",
    district: "Thanjavur (தஞ்சாவூர்)",
    taluk: "Thiruvaiyaru (திருவையாறு)",
    village: "Kandiyur (கண்டியூர்)",
    pattaNumber: "PATTA-1482/2026",
    surveyNumber: "SF-248/1A",
    totalLandAcreage: 6.5,
    isTenant: false,
    bankAccount: "IOBA-001048-7712",
    bankName: "Indian Overseas Bank - Thiruvaiyaru",
    ifscCode: "IOBA0001048",
    registrationTimestamp: "2026-08-15 10:30 AM",
    smsSent: true,
    sowing: {
      season: "Samba (சம்பா)",
      crop: "Paddy (நெல்)",
      variety: "CR-1009 Sub-1 (சன்ன ரகம்)",
      sowingDate: "2026-08-10",
      cropAreaAcres: 6.5,
      expectedYieldBags: 200,
      expectedYieldTons: 8.0,
      aiEstimatedRipeningDays: 130,
      aiPredictedHarvestStart: "15 Dec 2026",
      aiPredictedHarvestEnd: "25 Dec 2026",
      aiProcurementWindow: "Late December 2026",
    }
  },
  {
    id: "FARMER-102",
    registrationNumber: "TN-REG-2026-4822",
    aadhaarNumber: "7720 1198 3341",
    pmKisanId: "PMK-TN-441092",
    uzhavanId: "UZH-TRV-2026-4418",
    name: "Selvam Periyasamy (Tenant)",
    nameTa: "செல்வம் பெரியசாமி (குத்தகை)",
    phone: "+91 98422 11980",
    registrationOffice: "Mannargudi Agri Extension Centre",
    district: "Tiruvarur (திருவாரூர்)",
    taluk: "Mannargudi (மன்னார்குடி)",
    village: "Ashesam (அசேஷம்)",
    pattaNumber: "PATTA-TENANT-892",
    surveyNumber: "SF-112/3B",
    totalLandAcreage: 4.0,
    isTenant: true,
    bankAccount: "CBIN-028114-8890",
    bankName: "Canara Bank - Mannargudi Town",
    ifscCode: "CBIN0281140",
    registrationTimestamp: "2026-08-16 11:15 AM",
    smsSent: true,
    sowing: {
      season: "Samba (சம்பா)",
      crop: "Paddy (நெல்)",
      variety: "ADT-53 (சன்ன ரகம்)",
      sowingDate: "2026-08-12",
      cropAreaAcres: 4.0,
      expectedYieldBags: 150,
      expectedYieldTons: 6.0,
      aiEstimatedRipeningDays: 125,
      aiPredictedHarvestStart: "12 Dec 2026",
      aiPredictedHarvestEnd: "20 Dec 2026",
      aiProcurementWindow: "Mid December 2026",
    }
  },
  {
    id: "FARMER-103",
    registrationNumber: "TN-REG-2026-4823",
    aadhaarNumber: "9104 5541 2210",
    pmKisanId: "PMK-TN-552019",
    uzhavanId: "UZH-MDU-2026-7730",
    name: "Meenakshi Sundaram",
    nameTa: "மீனாட்சி சுந்தரம்",
    phone: "+91 97890 55412",
    registrationOffice: "Melur Primary Agricultural Cooperative Society",
    district: "Madurai (மதுரை)",
    taluk: "Melur (மேலூர்)",
    village: "Keelavalavu (கீழவளவு)",
    pattaNumber: "PATTA-5501/2026",
    surveyNumber: "SF-89/2",
    totalLandAcreage: 8.0,
    isTenant: false,
    bankAccount: "PUNB-018240-2210",
    bankName: "Punjab National Bank - Melur",
    ifscCode: "PUNB0182400",
    registrationTimestamp: "2026-08-18 02:45 PM",
    smsSent: true,
    sowing: {
      season: "Thaladi (தாளடி)",
      crop: "Paddy (நெல்)",
      variety: "BPT-5204 (ஆந்திரா பொன்னி)",
      sowingDate: "2026-08-20",
      cropAreaAcres: 8.0,
      expectedYieldBags: 250,
      expectedYieldTons: 10.0,
      aiEstimatedRipeningDays: 135,
      aiPredictedHarvestStart: "28 Dec 2026",
      aiPredictedHarvestEnd: "08 Jan 2027",
      aiProcurementWindow: "Early January 2027",
    }
  },
  {
    id: "FARMER-104",
    registrationNumber: "TN-REG-2026-4824",
    aadhaarNumber: "6610 9904 4410",
    pmKisanId: "PMK-TN-110481",
    uzhavanId: "UZH-CUD-2026-1194",
    name: "Karthik Ramachandran",
    nameTa: "கார்த்திக் ராமச்சந்திரன்",
    phone: "+91 99440 22891",
    registrationOffice: "Chidambaram Seed Distribution Station",
    district: "Cuddalore (கடலூர்)",
    taluk: "Chidambaram (சிதம்பரம்)",
    village: "Bhuvanagiri (புவனகிரி)",
    pattaNumber: "PATTA-3390/2026",
    surveyNumber: "SF-44/1",
    totalLandAcreage: 5.0,
    isTenant: false,
    bankAccount: "SBIN-005081-9904",
    bankName: "State Bank of India - Chidambaram",
    ifscCode: "SBIN0050812",
    registrationTimestamp: "2026-08-22 09:10 AM",
    smsSent: true,
    sowing: {
      season: "Kuruvai (குறுவை)",
      crop: "Paddy (நெல்)",
      variety: "Co-51 (பொது ரகம்)",
      sowingDate: "2026-05-15",
      cropAreaAcres: 5.0,
      expectedYieldBags: 120,
      expectedYieldTons: 4.8,
      aiEstimatedRipeningDays: 110,
      aiPredictedHarvestStart: "25 Aug 2026",
      aiPredictedHarvestEnd: "05 Sep 2026",
      aiProcurementWindow: "Ready Now (ஆகஸ்ட் இறுதி)",
    }
  }
];

export const INITIAL_DPC_CENTERS: DPCLocationCenter[] = [
  {
    id: "DPC-TNJ-VALLAM",
    name: "Thanjavur Main DPC - Vallam Road Yard",
    nameTa: "தஞ்சாவூர் தலைமை DPC - வல்லம் சாலை களம்",
    district: "Thanjavur (தஞ்சாவூர்)",
    taluk: "Thanjavur",
    village: "Vallam",
    address: "NH-83, Vallam Road Agri Yard, Thanjavur - 613403",
    gpsCoordinates: "10.7226° N, 79.0601° E",
    dailyCapacityTons: 350,
    currentProcuredTons: 330,
    remainingCapacityTons: 20,
    occupancyPercentage: 94,
    activeTruckQueue: 24,
    avgWaitMins: 110,
    status: "critical_overflow",
    inChargeName: "K. Rajendran, Assistant Manager (TNCSC)",
    contactPhone: "+91 4362 278190",
    availableGunnyBags: 12000,
    coveredStorageBags: 45000,
    capCoverPlinths: 6,
    lastUpdatedMinutesAgo: 6,
  },
  {
    id: "DPC-TNJ-KUMBA",
    name: "Kumbakonam Central DPC & Cap Yard",
    nameTa: "கும்பகோணம் மத்திய DPC & நெல் களம்",
    district: "Thanjavur (தஞ்சாவூர்)",
    taluk: "Kumbakonam",
    village: "Darasuram",
    address: "SH-64, Near Darasuram Railway Gate, Kumbakonam - 612702",
    gpsCoordinates: "10.9577° N, 79.3564° E",
    dailyCapacityTons: 280,
    currentProcuredTons: 110,
    remainingCapacityTons: 170,
    occupancyPercentage: 39,
    activeTruckQueue: 4,
    avgWaitMins: 15,
    status: "normal",
    inChargeName: "S. Govindaraj, Quality Inspector",
    contactPhone: "+91 435 2412800",
    availableGunnyBags: 18000,
    coveredStorageBags: 60000,
    capCoverPlinths: 8,
    lastUpdatedMinutesAgo: 12,
  },
  {
    id: "DPC-TRV-MANNAR",
    name: "Tiruvarur Mannargudi Junction DPC",
    nameTa: "திருவாரூர் மன்னார்குடி நேரடி கொள்முதல் மையம்",
    district: "Tiruvarur (திருவாரூர்)",
    taluk: "Mannargudi",
    village: "Mannargudi Town",
    address: "Pamani River Bank Road, Mannargudi - 614001",
    gpsCoordinates: "10.6653° N, 79.4449° E",
    dailyCapacityTons: 300,
    currentProcuredTons: 160,
    remainingCapacityTons: 140,
    occupancyPercentage: 53,
    activeTruckQueue: 9,
    avgWaitMins: 22,
    status: "normal",
    inChargeName: "M. Kavitha, Senior Quality Assayer",
    contactPhone: "+91 4367 222190",
    availableGunnyBags: 15000,
    coveredStorageBags: 40000,
    capCoverPlinths: 5,
    lastUpdatedMinutesAgo: 18,
  },
  {
    id: "DPC-NAG-COASTAL",
    name: "Nagapattinam Coastal Hub DPC",
    nameTa: "நாகப்பட்டினம் கடற்கரை கொள்முதல் களம்",
    district: "Nagapattinam (நாகப்பட்டினம்)",
    taluk: "Nagapattinam",
    village: "Vellipalayam",
    address: "East Coast Road, Near Port Authority Yard, Nagapattinam - 611001",
    gpsCoordinates: "10.7672° N, 79.8438° E",
    dailyCapacityTons: 220,
    currentProcuredTons: 60,
    remainingCapacityTons: 160,
    occupancyPercentage: 27,
    activeTruckQueue: 2,
    avgWaitMins: 10,
    status: "normal",
    inChargeName: "P. Muthusamy, Yard Superintendent",
    contactPhone: "+91 4365 248900",
    availableGunnyBags: 10000,
    coveredStorageBags: 30000,
    capCoverPlinths: 4,
    lastUpdatedMinutesAgo: 24,
  },
  {
    id: "DPC-CUD-CHIDAM",
    name: "Cuddalore Chidambaram Agri Depot DPC",
    nameTa: "கடலூர் சிதம்பரம் நேரடி கொள்முதல் மையம்",
    district: "Cuddalore (கடலூர்)",
    taluk: "Chidambaram",
    village: "Bhuvanagiri",
    address: "Vellar Basin Agri Complex, Bhuvanagiri, Chidambaram - 608001",
    gpsCoordinates: "11.3992° N, 79.6937° E",
    dailyCapacityTons: 240,
    currentProcuredTons: 95,
    remainingCapacityTons: 145,
    occupancyPercentage: 40,
    activeTruckQueue: 5,
    avgWaitMins: 18,
    status: "normal",
    inChargeName: "V. Balamurugan, Field Officer",
    contactPhone: "+91 4144 220194",
    availableGunnyBags: 14000,
    coveredStorageBags: 38000,
    capCoverPlinths: 5,
    lastUpdatedMinutesAgo: 10,
  },
  {
    id: "DPC-MDU-MELUR",
    name: "Madurai Melur Periyar Main DPC",
    nameTa: "மதுரை மேலூர் பெரியாறு கொள்முதல் மையம்",
    district: "Madurai (மதுரை)",
    taluk: "Melur",
    village: "Keelavalavu",
    address: "Tiruchy-Madurai Highway, Melur Bypass Yard, Madurai - 625106",
    gpsCoordinates: "10.0267° N, 78.3361° E",
    dailyCapacityTons: 260,
    currentProcuredTons: 75,
    remainingCapacityTons: 185,
    occupancyPercentage: 29,
    activeTruckQueue: 3,
    avgWaitMins: 12,
    status: "normal",
    inChargeName: "T. Ganesan, Senior Inspector",
    contactPhone: "+91 452 2481020",
    availableGunnyBags: 16000,
    coveredStorageBags: 42000,
    capCoverPlinths: 6,
    lastUpdatedMinutesAgo: 15,
  }
];

export const INITIAL_PROCUREMENT_APPOINTMENTS: ProcurementAppointment[] = [
  {
    id: "APT-9011",
    tokenNumber: "TN-TNJ-2026-9011",
    farmerId: "FARMER-101",
    farmerRegNumber: "TN-REG-2026-4821",
    farmerName: "Murugan Swaminathan",
    farmerNameTa: "முருகன் சுவாமிநாதன்",
    phone: "+91 94431 82910",
    dpcId: "DPC-TNJ-VALLAM",
    dpcName: "Thanjavur Main DPC - Vallam Road Yard",
    dpcNameTa: "தஞ்சாவூர் தலைமை DPC",
    district: "Thanjavur",
    taluk: "Thiruvaiyaru",
    paddyType: "Paddy Grade A (சன்ன ரகம்)",
    variety: "CR-1009 Sub-1",
    gunnyBagsCount: 200,
    estimatedTons: 8.0,
    actualTons: 8.0,
    grossWeightKg: 12400,
    tareWeightKg: 4400,
    appointmentDate: "Today (31 Aug 2026)",
    appointmentTimeSlot: "10:00 AM - 11:00 AM",
    transportMode: "Tractor (டிராக்டர்)",
    vehicleNumber: "TN-49-AB-2410",
    status: "arrived",
    moisturePercentage: 15.4,
    foreignMatterPercentage: 0.8,
    qualityPassed: true,
    mspRatePerQuintal: 2320,
    tnStateBonusPerQuintal: 100, // Total = ₹2,420
    totalPayoutAmount: 193600,
    epasSlipNumber: "EPAS-TNCSC-2026-44910",
    hourlyReminderSmsCount: 2,
    createdAt: "2026-08-31 07:00 AM",
  },
  {
    id: "APT-9012",
    tokenNumber: "TN-TRV-2026-9012",
    farmerId: "FARMER-102",
    farmerRegNumber: "TN-REG-2026-4822",
    farmerName: "Selvam Periyasamy (Tenant)",
    farmerNameTa: "செல்வம் பெரியசாமி (குத்தகை)",
    phone: "+91 98422 11980",
    dpcId: "DPC-TRV-MANNAR",
    dpcName: "Tiruvarur Mannargudi Junction DPC",
    dpcNameTa: "திருவாரூர் மன்னார்குடி DPC",
    district: "Tiruvarur",
    taluk: "Mannargudi",
    paddyType: "Paddy Grade A (சன்ன ரகம்)",
    variety: "ADT-53",
    gunnyBagsCount: 150,
    estimatedTons: 6.0,
    appointmentDate: "Today (31 Aug 2026)",
    appointmentTimeSlot: "11:00 AM - 12:00 PM",
    transportMode: "Mini Lorry (மினி லாரி)",
    vehicleNumber: "TN-50-E-9912",
    status: "booked",
    mspRatePerQuintal: 2320,
    tnStateBonusPerQuintal: 100,
    hourlyReminderSmsCount: 1,
    createdAt: "2026-08-31 07:30 AM",
  },
  {
    id: "APT-9008",
    tokenNumber: "TN-MDU-2026-9008",
    farmerId: "FARMER-103",
    farmerRegNumber: "TN-REG-2026-4823",
    farmerName: "Meenakshi Sundaram",
    farmerNameTa: "மீனாட்சி சுந்தரம்",
    phone: "+91 97890 55412",
    dpcId: "DPC-TNJ-KUMBA",
    dpcName: "Kumbakonam Central DPC & Cap Yard",
    dpcNameTa: "கும்பகோணம் DPC",
    district: "Thanjavur",
    taluk: "Kumbakonam",
    paddyType: "Paddy Grade A (சன்ன ரகம்)",
    variety: "BPT-5204",
    gunnyBagsCount: 250,
    estimatedTons: 10.0,
    actualTons: 10.0,
    grossWeightKg: 14800,
    tareWeightKg: 4800,
    appointmentDate: "Today (31 Aug 2026)",
    appointmentTimeSlot: "09:00 AM - 10:00 AM",
    transportMode: "Tractor (டிராக்டர்)",
    vehicleNumber: "TN-58-M-4418",
    status: "dbt_credited",
    moisturePercentage: 14.8,
    foreignMatterPercentage: 0.6,
    qualityPassed: true,
    mspRatePerQuintal: 2320,
    tnStateBonusPerQuintal: 100,
    totalPayoutAmount: 242000,
    dbtTxnId: "PFMS-TNCSC-20260831-8841029",
    dbtCreditedAt: "Today 09:45 AM (Within 48 hrs)",
    epasSlipNumber: "EPAS-TNCSC-2026-11048",
    hourlyReminderSmsCount: 2,
    createdAt: "2026-08-31 06:15 AM",
  }
];

export const INITIAL_TALUK_OVERFLOW_METRICS: TalukOverflowMetric[] = [
  {
    taluk: "Thiruvaiyaru (திருவையாறு)",
    district: "Thanjavur",
    totalProcurementDemandTons: 92000,
    existingDpcCapacityTons: 58000,
    overflowDeficitTons: 34000,
    overflowFrequency: "Severe (Every Season)",
    recommendedNewDpcLocations: [
      "Kandiyur Road Extension DPC",
      "Thillaisthanam River Basin Yard",
      "Melathiruppanthuruthi Cap Yard"
    ],
    lastYearProcuredTons: 84000,
    currentYearProcuredTons: 92000,
    procurementGrowthPercent: 9.5,
    priceAdjustmentRecommendation: "High yield season (+9.5% YoY). Maintain MSP + State Bonus of ₹2,420/qtl to incentivize fast delta clearance.",
  },
  {
    taluk: "Mannargudi (மன்னார்குடி)",
    district: "Tiruvarur",
    totalProcurementDemandTons: 78000,
    existingDpcCapacityTons: 52000,
    overflowDeficitTons: 26000,
    overflowFrequency: "High",
    recommendedNewDpcLocations: [
      "Ashesam Junction DPC",
      "Vaduvur Lake Basin Yard"
    ],
    lastYearProcuredTons: 71000,
    currentYearProcuredTons: 78000,
    procurementGrowthPercent: 9.8,
    priceAdjustmentRecommendation: "Normal arrival rate. Recommend setting up 2 satellite DPC sheds at Pamani basin.",
  },
  {
    taluk: "Chidambaram (சிதம்பரம்)",
    district: "Cuddalore",
    totalProcurementDemandTons: 48000,
    existingDpcCapacityTons: 36000,
    overflowDeficitTons: 12000,
    overflowFrequency: "Moderate",
    recommendedNewDpcLocations: [
      "Bhuvanagiri Vellar Basin DPC",
      "Parangipettai Coastal Shed"
    ],
    lastYearProcuredTons: 52000,
    currentYearProcuredTons: 48000,
    procurementGrowthPercent: -7.6,
    priceAdjustmentRecommendation: "Procurement down 7.6% due to early rainfall. Government can consider special ₹50 bonus in G.O. to support affected farmers.",
  }
];

export const INITIAL_SMS_LOGS: SMSLog[] = [
  {
    id: "SMS-101",
    sender: "TN-AGRI-OFFICE",
    timestamp: "10:31 AM",
    recipientPhone: "+91 94431 82910",
    farmerName: "Murugan Swaminathan",
    type: "office_registration",
    contentTa: "தமிழ்நாடு வேளாண்மை & கூட்டுறவு வங்கி பதிவு: திரு. முருகன், உங்கள் பதிவு எண் TN-REG-2026-4821. சாகுபடி: 6.5 ஏக்கர் (சம்பா நெல் CR-1009). AI அறுவடை கணக்கீடு: 15 Dec 2026. அறுவடைக்கு முன் DPC நேரடி கொள்முதல் நாள் முன்பதிவு செய்யவும்.",
    contentEn: "Govt of Tamil Nadu Agri Registration: Mr. Murugan, Reg No TN-REG-2026-4821 confirmed. Sown: 6.5 Acres Samba Paddy. AI Ripening forecast: 15 Dec 2026. Book DPC procurement appointment prior to harvest.",
  },
  {
    id: "SMS-102",
    sender: "TN-TNCSC-DPC",
    timestamp: "09:00 AM",
    recipientPhone: "+91 94431 82910",
    farmerName: "Murugan Swaminathan",
    type: "hourly_slot_reminder",
    contentTa: "DPC நேரடி கொள்முதல் நினைவூட்டல்: டோக்கன் TN-TNJ-2026-9011. உங்கள் 10:00 AM - 11:00 AM ஸ்லாட்டிற்கு இன்னும் 1 மணி நேரம் உள்ளது. 200 மூட்டைகளுடன் தஞ்சாவூர் வல்லம் DPC எடை மேடைக்கு வரவும்.",
    contentEn: "TNCSC DPC Reminder: Token TN-TNJ-2026-9011. 1 hour remaining for your 10:00 AM - 11:00 AM slot. Arrive with 200 bags at Thanjavur Vallam DPC weighbridge.",
  },
  {
    id: "SMS-103",
    sender: "TN-PFMS-DBT",
    timestamp: "09:45 AM",
    recipientPhone: "+91 97890 55412",
    farmerName: "Meenakshi Sundaram",
    type: "dbt_credit",
    contentTa: "TNCSC நேரடி வங்கி வரவு: 100 குவிண்டால் சன்ன ரக நெல்லுக்கு ₹2,42,000 (MSP ₹2320 + TN ஊக்கத்தொகை ₹100) உங்கள் கணக்கில் 48 மணி நேரத்திற்குள் நேரடியாக செலுத்தப்பட்டது. UTR: PFMS-TNCSC-20260831-8841029.",
    contentEn: "TNCSC DBT Credit: ₹2,42,000 credited within 48 hrs for 100 qtl Grade A Paddy as per G.O. Ms 148. UTR: PFMS-TNCSC-20260831-8841029.",
  }
];
